name: backend_app

dependencies:
  - python==3.7
  - psycopg2
  - pip=21.0
  - pip:
      - Django
      - gunicorn
      - djangorestframework==3.12
      - djangorestframework-simplejwt==4.6
      - Pillow==8.1
      - drf-yasg==1.20.0
      - flake8==3.9
      - django-cors-headers==3.7
