# Generated by Django 3.1.7 on 2021-03-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='action',
            field=models.CharField(choices=[('RE', 'Registration Email'), ('PW', 'Password Reset')], default='RE', max_length=2),
        ),
    ]
