# Generated by Django 3.1.7 on 2021-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_request', '0004_auto_20210323_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=32),
        ),
    ]
